### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by yesszus**
Add a pharses and lang codes.

### CODE REVIEW

**Comment by CaMer0n** [comment]
Thank you @yesszus ! It looks good, but why did you remove LICENSE.txt ?

**Comment by CaMer0n** [comment]
Also, these defines (below) do not need to be `global` as they are only used in youtube.php. So, they should be moved to English_front.php 

+define("LAN_YOUTUBE_SUBSCRIBE_CHANNEL", "Subscribe to this Channel");
+define("LAN_YOUTUBE_NONE_AVAILABLE", "None available!");
+define("LAN_YOUTUBE_BAD_LINK", "Bad Link!");

.. and numbered as LAN_YOUTUBE_001, LAN_YOUTUBE_002 etc.

**Comment by yesszus** [comment]
I accidentally deleted LICENSE.txt
Updated all lang files, admin_config.php and youtube.php.

**Comment by CaMer0n** [comment]
Thank you, I will make some minor changes.

**Pull request merged**
